version: "3.9"

services:
    api:
        container_name: serversolution 
        restart: always
        build: .
        ports:
            - "3000:8080"
      
        volumes:
          - .:/usr/src/app
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
           - "27017:27017"
    
